services:
  custom_homepage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3034:3034"
    environment:
      PORT: "3034"
      NODE_ENV: production
    restart: unless-stopped
