services:
  custom_homepage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    environment:
      PORT: "3033"
      DB_FILE: "/data/settings.db"
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - ./:/app
      - homepage_node_modules:/app/node_modules
      - homepage_data:/data
    restart: unless-stopped

volumes:
  homepage_node_modules:
  homepage_data:
