services:
  custom_homepage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
      - "3034:3034"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  node_modules:
